fix: docker entrypoint/command to kube command/args
dohsimpson/docker2kube pull request #1
Opened 2024-02-18 21:29 UTC by sharevb

As referred in https://github.com/CorentinTh/it-tools/pull/890#issuecomment-1951434667 :
- `entrypoint` in Docker Compose is `command` in Kubernetes
- `command` in Docker Compose is `args` in Kubernetes

2024-02-18 21:30 UTC, sharevb commented
Hi @dohsimpson, thanks for this wonderful package ! Just a little mistake as stated in https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#define-a-command-and-arguments-when-you-create-a-pod

2024-02-19 00:18 UTC, dohsimpson commented
Hi @sharevb, love your work on composerize, I use it all the time!

PR looks good, made a comment on a small semantic change. Thanks for the fix!

2024-02-19 07:00 UTC, sharevb commented
Hi @dohsimpson, sorry dont see where you left a comment

2024-02-20 03:38 UTC, dohsimpson requested changes

2024-02-20 03:38 UTC, dohsimpson commented on test/index.test.ts
> +        entrypoint: /bin/sh
One minor issue, when running ` /bin/sh echo hello world` I got error `/bin/echo: /bin/echo: cannot execute binary file`. Could you update it so that the command is semantically correct:

```
entrypoint: echo
command: hello world
```

2024-02-20 03:39 UTC, dohsimpson commented
> Hi @dohsimpson, thanks :) but sorry dont see where you left a comment

Apologies, review was in pending state, it should be visible now

2024-02-21 04:43 UTC, merged

2024-02-21 04:43 UTC, dohsimpson commented
Thank you, PR is merged!

2024-02-21 22:11 UTC, sharevb commented
Hi @dohsimpson, thanks :) could you please publish new version to npm ? thanks

2024-02-22 21:11 UTC, dohsimpson commented
> Hi @dohsimpson, thanks :) could you please publish new version to npm ? thanks

Published, please use version 0.0.14